<a href="https://colab.research.google.com/github/seohy20251243/BDA-/blob/main/BDA4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# row_stack 과 vstack()

In [10]:
import numpy as np
a= np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
b= np.arange(1,5)
b

array([1, 2, 3, 4])

In [12]:
np.row_stack((a,b))

/tmp/ipykernel_197/1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

# np.r_[]

In [1]:
import  numpy as np
a= np.array([1,2,3])
b= np.array([4,5,6])

In [2]:
np.r_[a,0,0,b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [3]:
np.r_[3:10:3, [0]*2,5,6]

array([3, 6, 9, 0, 0, 5, 6])

In [4]:
np.r_[-1:1:6j, [0]*2,5,6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [5]:
np.linspace(-1,1,6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

# np.r_['i',a.b]

In [6]:
a=np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
np.r_[a,a,a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [8]:
np.r_ ['0',a,a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

# 난수 제너레이터의 함수

In [15]:
import numpy as np

rg=np.random.default_rng(12345)
rg

Generator(PCG64) at 0x7E21836A58C0

In [16]:
r= rg.random
r

<bound method Generator.random of Generator(PCG64) at 0x7E21836A58C0>

In [17]:
rg.random(5)

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955])

In [18]:
rg.random((4,3))

array([[0.33281393, 0.59830875, 0.18673419],
       [0.67275604, 0.94180287, 0.24824571],
       [0.94888115, 0.66723745, 0.09589794],
       [0.44183967, 0.88647992, 0.6974535 ]])

# 난수 제너레이터 함수 integers()

In [19]:
import numpy as np
rg= np.random.default_rng(12345)
r=rg.integers(low=0, high=10, size=3)
r

array([6, 2, 7])

In [20]:
rg.integers(1,7,(3,4))

array([[2, 2, 5, 4],
       [5, 6, 3, 6],
       [2, 4, 4, 2]])

# 난수 생성자 함수

In [21]:
import numpy as np
rg= np.random.default_rng(seed=42)
rg.standard_normal(10)

array([ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472, -1.95103519,
       -1.30217951,  0.1278404 , -0.31624259, -0.01680116, -0.85304393])

In [22]:
rg.standard_normal((4,3))

array([[ 0.87939797,  0.77779194,  0.0660307 ],
       [ 1.12724121,  0.46750934, -0.85929246],
       [ 0.36875078, -0.9588826 ,  0.8784503 ],
       [-0.04992591, -0.18486236, -0.68092954]])