<a href="https://colab.research.google.com/github/seohy20251243/BDA-/blob/main/bda_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 03 과학용 컴퓨팅 패키지 numpy

numpy: 데이터 분석, 기계학습, 신호처리 등 핵심 라이브러리

ndarray: numpy 다루는 대표적인 자료형

In [ ]:
import numpy as np
a= np.arange(3)
a

array([0, 1, 2])

In [ ]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [ ]:
a=np.arange (1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b=np.full_like(a,[1,2,3])
b

array([[1, 2, 3],
       [1, 2, 3]])

## 배열함수

a.sum() >> 모든 원소의 함
a.sum(axis=0) >> 열 합 배열
a.sum(axis=1)>> 행 합 배열

In [ ]:
a = np.array([[3,5,8],[1,2,3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [ ]:
a.cumsum(axis=0)

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [ ]:
a.cumsum(axis=1)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

In [ ]:
import numpy as np
a= np.power(np.arange(10),2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
print(a[3])
print(a[-2])

9
64


In [ ]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [ ]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


# 역순과 대입

In [ ]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [ ]:
a[::-2]

array([81, 49, 25,  9,  1])

In [ ]:
a[2:5]=-100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [ ]:
a[2:5]=[-5,-5,-5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [ ]:
a[2:5]=[-5,-5,-5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

# 2차원 배열의 첨자와 슬라이싱

행 반환: x[row]

열 반환: x[:,col]

원소 반환: x[row,col]

In [ ]:
a=np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [ ]:
a[2,4]

np.int64(16)

In [ ]:
a[2][4]

np.int64(16)

In [ ]:
a[1:2,2:5]

array([[ 8,  9, 10]])

In [ ]:
a= np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# 브로드캐스팅

In [ ]:
a=np.array([3,4,5])
b=np.array([8,7,6])
a+b


array([11, 11, 11])

In [ ]:
from numpy import arange
x= arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y= arange(-1,2)
y

array([-1,  0,  1])

In [ ]:
x*y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [ ]:
x+y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [ ]:
from numpy import arange
x= arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y= arange(3,10,3).reshape(3,1)
y

array([[3],
       [6],
       [9]])

In [ ]:
x/y

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

In [ ]:
x-y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [ ]:
from numpy import arange
x= arange(1,4)
x

array([1, 2, 3])

In [ ]:
y= arange(1,4).reshape(3,1)
y

array([[1],
       [2],
       [3]])

In [ ]:
x*y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [ ]:
x/y

array([[1.        , 2.        , 3.        ],
       [0.5       , 1.        , 1.5       ],
       [0.33333333, 0.66666667, 1.        ]])

In [ ]:
from numpy import arange

x= arange(0,10,3).reshape(4,1)
x

array([[0],
       [3],
       [6],
       [9]])

In [ ]:
y=arange(1,3)
y

array([1, 2])

In [ ]:
x*y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [ ]:
x+y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

# 고급색인